import img1 from './assets/imghd/img00001.jpg';
import img2 from './assets/imghd/img00002.jpg';
import img3 from './assets/imghd/img00003.jpg';
import img4 from './assets/imghd/img00004.jpg';
import img5 from './assets/imghd/img00005.jpg';
import img6 from './assets/imghd/img00006.jpg';
import img7 from './assets/imghd/img00007.jpg';
import img8 from './assets/imghd/img00008.jpg';
import img9 from './assets/imghd/img00009.jpg';
import img10 from './assets/imghd/img00010.jpg';
import img11 from './assets/imghd/img00011.jpg';
import img12 from './assets/imghd/img00012.jpg';
import img13 from './assets/imghd/img00013.jpg';
import img14 from './assets/imghd/img00014.jpg';
import img15 from './assets/imghd/img00015.jpg';
import img16 from './assets/imghd/img00016.jpg';
import img17 from './assets/imghd/img00017.jpg';
import img18 from './assets/imghd/img00018.jpg';
import img19 from './assets/imghd/img00019.jpg';
import img20 from './assets/imghd/img00020.jpg';
import img21 from './assets/imghd/img00021.jpg';
import img22 from './assets/imghd/img00022.jpg';
import img23 from './assets/imghd/img00023.jpg';
import img24 from './assets/imghd/img00024.jpg';
import img25 from './assets/imghd/img00025.jpg';
import img26 from './assets/imghd/img00026.jpg';
import img27 from './assets/imghd/img00027.jpg';
import img28 from './assets/imghd/img00028.jpg';
import img29 from './assets/imghd/img00029.jpg';
import img30 from './assets/imghd/img00030.jpg';
import img31 from './assets/imghd/img00031.jpg';
import img32 from './assets/imghd/img00032.jpg';
import img33 from './assets/imghd/img00033.jpg';
import img34 from './assets/imghd/img00034.jpg';
import img35 from './assets/imghd/img00035.jpg';
import img36 from './assets/imghd/img00036.jpg';
import img37 from './assets/imghd/img00037.jpg';
import img38 from './assets/imghd/img00038.jpg';
import img39 from './assets/imghd/img00039.jpg';
import img40 from './assets/imghd/img00040.jpg';
import img41 from './assets/imghd/img00041.jpg';
import img42 from './assets/imghd/img00042.jpg';
import img43 from './assets/imghd/img00043.jpg';
import img44 from './assets/imghd/img00044.jpg';
import img45 from './assets/imghd/img00045.jpg';
import img46 from './assets/imghd/img00046.jpg';
import img47 from './assets/imghd/img00047.jpg';
import img48 from './assets/imghd/img00048.jpg';
import img49 from './assets/imghd/img00049.jpg';
import img50 from './assets/imghd/img00050.jpg';
import img51 from './assets/imghd/img00051.jpg';
export const projects = [
	{
		id: 1,
		url: 'Generoso Den',
		col: 'col-1',
		imgs: img4,
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color.\nUn espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		id: 2,
		url: 'Frank into Frank',
		col: 'col-2',
		imgs: img14,
		location: 'Nueva York, Estados Unidos de América.',
		date: 'Julio de 2017',
		shot: 'Lumix DMC FZ200',
		text: 'Detalle de escenario distópico.\nGuggenheim de Frank Lloyd Wright. ¿Y si se soluciona un escenario de ese tipo, sin llegar al extremo utópico?\nRealidad y normalidad.',
	},
	{
		id: 3,
		url: 'Complejidad gris MU-U',
		col: 'col-2',
		imgs: img6,
		location: 'Berlín, Alemania.',
		date: 'Abril de 2012',
		shot: 'Kodak Z980 + S + S',
		text: 'Entrañas multiplicadas para sostener la historia. De aparente libre disposición, pero estrictas en su rigidez y tensión.\nFotografía realizada en un maravilloso viaje en el que a la 4ª fue la vencida y se venció. Biennale de Berlín, de arriba para abajo, al centro y... Mucha vida. Museo Judío de Daniel Libeskind.\n',
	},
	{
		id: 4,
		url: 'El Juicio Inicial',
		col: 'col-3',
		imgs: img17,
		location: 'Nueva York, EE. UU.',
		date: 'Julio de 2017',
		shot: 'Panasonic DMC-FZ200',
		text: 'Los juicios iniciales y los juicios finales… Y los juicios intermedios.Estación World Trade Center de Santiago Calatrava. Representación de El Juicio Final de la Capilla Sixtina de Miguel Ángel.',
	},
	{
		id: 5,
		url: 'Sugerencia de Altura',
		col: 'col-3',
		imgs: img12,
		location: 'Madrid, España',
		date: 'Abril de 2012',
		shot: 'Kodak Z980',
		text: 'La antigua catedral, desde la parte nueva del museo. Lavapiés profundizado resalta alegre como siempre. Alguien me decía hace poco que siempre hacemos la misma fotografía. Fotografía tomada desde la planta bajocubierta del edificio de la ampliación del Museo Nacional Centro de Arte Reina Sofía, obra de Jean Nouvel. Inspiración de Nano, nacida de buenos actos, buenas palabras, y entretenimientos comunes.',
	},
	{
		id: 6,
		url: 'Suave Dureza',
		col: 'col-4',
		imgs: img9,
		location: 'Tokio, Japón',
		date: 'Noviembre de 2017',
		shot: 'Sony DSC-RX 10M4',
		text: 'El tamiz de una circunstancia, una curva y su contra curva… y un tronco cono de hormigón. Todo ello puede ser una suave dureza o una dura suavidad. El sol y las nubes tendrán que opinar al respecto. A la segunda llegué a Tokio. Lugar para vivirlo y no visitarlo, como pocos he experimentado. Eléctrico y electrónico. Llegué con buenos pre conocimientos e intereses y me guiaron además con algunas rutas fabianosas fruto de valiosas derivas. National Art Center de Kisho Kurokawa.',
	},
	{
		id: 7,
		url: 'Gracias',
		col: 'col-5',
		imgs: img8,
		location: 'Colonia, Alemania',
		date: 'Noviembre de 2014',
		shot: 'Panasonic DMC-FZ200',
		text: 'Reflexión de dos gracias en un espacio muy gracioso y un entorno de gratitud y felicidad. Volúmenes entendidos con sencillez y perfección, detallados por luces y reflexiones y personalizados por dos figuras. Fotografía tomada en el museo Kolumba de arte sacro, obra del arquitecto suizo Peter Zumthor, en un viaje al que fui invitado por una gran persona, a celebrar el cumpleaños de otras grandes personas, y donde en todo momento estuve rodeado de grandes personas, generosas, amables. Gran tranquilidad, felicidad y disfrute.',
	},
	{
		id: 8,
		url: 'Oculus Detail 02',
		col: 'col-4',
		imgs: img5,
		location: 'Nueva York, EE. UU.',
		date: 'Julio de 2017',
		shot: 'Nikon D2X',
		text: 'La curva de la forma y de la luz. Estación World Trade Center de Santiago Calatrava. Con las arquitecturas disfruto paseando en soledad, yo soy paciente, ellas también, no hay conflicto… mientras no piense en otras con las que no estoy.',
	},
	{
		id: 9,
		url: 'Inside Renzo',
		col: 'col-6',
		imgs: img18,
		location: 'Nueva York, EE. UU.',
		date: 'Julio de 2017',
		shot: 'Nikon D2X',
		text: 'Descenso luminoso estridente. Poco que añadir. Bueno, hay reflejos. Instalación de Ajay Kurian en la caja de la escalera del Whitney Museum de Renzo Piano.',
	},
	{
		id: 10,
		url: 'Hermandad de Nocturnidades Alineadas',
		col: 'col-7',
		imgs: img26,
		location: 'Madrid, España',
		date: 'Septiembre de 2014',
		shot: 'Nikon D2X',
		text: 'Un arquitecto se fue a dormir esa noche. Cuadrícula diagonal bien proyectada, en la noche, en la mente y en su entorno directo. Edificio de Génova 17 de la Hermandad de Arquitectos, de Antonio Ruiz Barbarín. Siempre interesante que te encarguen cosas analizables.',
	},
	{
		id: 11,
		url: 'Moneo me lo Regaló',
		col: 'col-6',
		imgs: img19,
		location: 'Mérida, España',
		date: 'Diciembre de 2016',
		shot: 'Lumix DMC FZ200',
		text: 'Icónica e histórica diagonal. Las buenas compañías traen la luz. Alegrías extremeñas gracias a Gracia y a Fabiana. Primavera en otoño, otoño en otoño. Museo Nacional de Arte Romano de Rafael Moneo.',
	},
	{
		id: 12,
		url: 'Interiores con Final 02',
		col: 'col-8',
		imgs: img15,
		location: 'Sevilla, España',
		date: 'Noviembre de 2014',
		shot: 'Lumix DMC FZ200',
		text: 'Reflexiones subterráneas de la historia. Simetrías que se contraponen al paso de los diferentes estilos artísticos que fueron moldeando el palacio real en uso más antiguo de Europa. Fotografía tomada en un viaje sorpresa para felicitar a un sevillano señor Barbosa. Reales Alcázares de Sevilla. lidad, felicidad y disfrute.',
	},
	{
		id: 13,
		url: 'Nostalgia Tokiota',
		col: 'col-9',
		imgs: img7,
		location: 'Tokio, Japón',
		date: 'Enero de 2020',
		shot: 'Sony DSC-RX 10M4',
		text: 'Densa suavidad. Fotografía tomada desde lo alto de la torre Mori. Acompañado por un tridente volador.',
	},
	{
		id: 14,
		url: 'Escape Room Again',
		col: 'col-10',
		imgs: img31,
		location: 'Rodalquilar, España',
		date: 'Marzo de 2019',
		shot: 'Sony DSC-RX 10M4',
		text: 'Ocasos dorados que no terminan de retirarse. Se tatúan y procrean en su aparente abandono. De forma y estilo, estetas. Mina de oro abandonada en Rodalquilar. De nuevo una escapada agradabilísima, una escapada con resultados.',
	},
	{
		id: 15,
		url: 'Sin título',
		col: 'col-11',
		imgs: img2,
		location: '',
		date: '',
		shot: '',
		text: '',
	},
	{
		id: 16,
		url: 'Contrastes Arquitectónicos al Amarillo',
		col: 'col-12',
		imgs: img20,
		location: 'Madrid, España',
		date: 'Febrero de 2019',
		shot: 'Sony DSC-RX 10M4',
		text: 'Entramado de luz matinal y soluciones ordenadamente liosas. Interior del edificio Medialab-Prado, de Langarita-Navarro. Fotografía realizada durante una serie de paseos arquitectónicos madrileños.',
	},
	{
		id: 17,
		url: 'Di Nuovo Gesù 02',
		col: 'col-9',
		imgs: img23,
		location: 'Nápoles, Italia',
		date: 'Junio de 2019',
		shot: 'Sony DSC-RX 10M4',
		text: 'Barroco iluminado. La luz y la alegría que me sigue aportando Italia en cada visita, a chorros y raudales. Chiesa del Gesù Nuovo, de Novello de San Lucano, Giuseppe Valeriano y Pietro Provedi. Guía napoletana de primera categoría, Antonella.',
	},
	{
		id: 18,
		url: 'Ciclos Porcelánicos',
		col: 'col-6',
		imgs: img10,
		location: 'Villareal, España',
		date: 'Febrero de 2019',
		shot: 'Sony DSC-RX 10M4',
		text: 'Dos, uno, dos, dos, en doscientos dieciséis. Fábrica de Porcelanosa, invitados por Leticia y paseo de Lords.',
	},
	{
		id: 19,
		url: 'Licor Iluminado',
		col: 'col-7',
		imgs: img22,
		location: 'Madrid, España.',
		date: 'Julio de 2012',
		shot: 'Nikon D2X',
		text: 'Puntos de luz, puntos de vida. Cava del Club Santo Domingo, del estudio Arquitectura Norte',
	},
	{
		id: 20,
		url: '21 21 at 14:28',
		col: 'col-7',
		imgs: img25,
		location: 'Tokio, Japón',
		date: 'Noviembre de 2017',
		shot: 'Sony DSC-RX 10M4',
		text: '21 21 Design Sight de Tadao Ando. Poco después de ver una de las exposiciones que más he disfrutado nunca, Tadao Ando: Endeavors. Sí, la vida requiere de esfuerzos, de muchos, así que mejor que te guste por lo que te esfuerzas.',
	},
	{
		id: 21,
		url: 'Proyecciones Aserradas',
		col: 'col-13',
		imgs: img28,
		location: 'Beacon, EE. UU.',
		date: 'Septiembre de 2018',
		shot: 'Sony DSC-RX 10M4',
		text: 'Ortogonalidades deslizándose por férreas curvas hasta alcanzar la oscuridad y volver por donde empezaron de manera más tenue. Excursión principalmente escultural remontando el río Hudson y kilómetros y toneladas de enriquecedora y gustosa actividad. Museo Dia en Beacon.',
	},
	{
		id: 22,
		url: 'Dura Suavidad',
		col: 'col-6',
		imgs: img24,
		location: 'Tokio, Japón',
		date: 'Noviembre de 2017',
		shot: 'Sony DSC-RX 10M4',
		text: 'El tamiz de una circunstancia, una curva y su contra curva… y un tronco cono de hormigón. Todo ello puede ser una suave dureza o una dura suavidad. El sol y las nubes tendrán que opinar al respecto. A la segunda llegué a Tokio. Lugar para vivirlo y no visitarlo, como pocos he experimentado. Eléctrico y electrónico. Llegué con buenos conocimientos e intereses y me guiaron con rutas fabianosas. National Art Center de Kisho Kurokawa.',
	},
	{
		id: 23,
		url: 'Infiltración Cilíndrica',
		col: 'col-6',
		imgs: img29,
		location: 'Braga, Portugal',
		date: 'Agosto de 2014',
		shot: 'Nikon D2X',
		text: 'Simplicidades y tecnicismos… planos, círculos y mecanismos…  Cilindro de aire que traspasa el volumen creado por costillas verticales de hormigón. Armonía en paz, preparada para el bullicio. Fotografía realizada tras el salto de la valla que mantiene el Estadio Municipal de Braga (obra de Eduardo Souto de Moura) en calma y vacío durante los días previos a los partidos del Sporting. En la gran compañía de Rocío, la que me precipitó a esquivar las órdenes del guardia de seguridad y por la que existe esta foto.',
	},
	{
		id: 24,
		url: 'Pacific Red II con Desagüe en Esquina, Politomado',
		col: 'col-8',
		imgs: img16,
		location: 'Nueva York, EE. UU.',
		date: 'Julio de 2017',
		shot: 'Lumix DMC FZ200',
		text: 'Perfecta imperfección de doble reflejo en cubo dentro de cubo con gradientes de transparencias que concluyen en malla de retícula cuadrada… Todo ello bajo una ambiciosa perspectiva caballera. Politomada. Obra de Larry Bell instalada en una de las terrazas del Whitney Museum de Renzo Piano.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-12',
		imgs: 'imgs00048.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-14',
		imgs: 'imgs00047.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-9',
		imgs: 'imgs00039.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-15',
		imgs: 'imgs00036.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-7',
		imgs: 'imgs00043.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-6',
		imgs: 'imgs00046.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-13',
		imgs: 'imgs00038.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-16',
		imgs: 'imgs00037.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-5',
		imgs: 'imgs00034.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-3',
		imgs: 'imgs00003.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-8',
		imgs: 'imgs00011.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-9',
		imgs: 'imgs00032.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-12',
		imgs: 'imgs00042.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-6',
		imgs: 'imgs00030.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-17',
		imgs: 'imgs00041.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-18',
		imgs: 'imgs00044.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-17',
		imgs: 'imgs00033.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-19',
		imgs: 'imgs00049.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-19',
		imgs: 'imgs00051.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-6',
		imgs: 'imgs00040.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-8',
		imgs: 'imgs00021.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-21',
		imgs: 'imgs00013.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-18',
		imgs: 'imgs00050.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-4',
		imgs: 'imgs00027.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		col: 'col-5',
		imgs: 'imgs00045.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		imgs: 'imgs00001.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
	{
		url: 'Generoso DEN',
		imgs: 'imgs00035.jpg',
		location: 'Copenhague, Dinamarca',
		date: 'Mayo de 2013',
		shot: 'Nikon D2X, lente 20.0 mm f/2.0',
		text: 'La calma y sobriedad contrastadas por la vitalidad, vibración, energía y color. Un espacio cambiante y absorbente, donde cabe la creatividad y el orden nórdico. Esta fotografía pudo ser tomada gracias a la generosidad de la banda de música electrónica Den Sorte Skole y también al cámara que estaba grabando el previo al concierto, quien me abrió las puertas del teatro al observar mi curiosidad, lo cual concluyó en que me regalaran unas entradas junto al palco real, para ver su concierto. Royal Danish Playhouse de Lundgaard & Tranberg.',
	},
];
